# Generated by Django 6.0.5 on 2026-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=50, unique=True, verbose_name='Kode Barang')),
                ('nama_produk', models.CharField(max_length=255, verbose_name='Nama Produk')),
                ('kategori', models.CharField(choices=[('Dress', 'Dress'), ('Oneset', 'Oneset'), ('Hijab', 'Hijab'), ('Perlengkapan Hijab', 'Perlengkapan Hijab'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50, verbose_name='Kategori')),
                ('satuan', models.CharField(choices=[('pcs', 'Pcs'), ('lusin', 'Lusin'), ('kodi', 'Kodi')], default='pcs', max_length=20, verbose_name='Satuan')),
                ('stok', models.IntegerField(default=0, verbose_name='Stok')),
                ('stok_minimum', models.IntegerField(default=0, verbose_name='Stok Minimum')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Daftar Barang',
                'ordering': ['nama_produk'],
            },
        ),
    ]
