# Generated by Django 6.0.5 on 2026-05-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('deskripsi', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Daftar Kategori',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150, unique=True, verbose_name='Nama Supplier')),
                ('kontak', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kontak (Telepon/WA)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Daftar Supplier',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barang_list', to='inventory.kategori', verbose_name='Kategori'),
        ),
    ]
