# Generated by Django 6.0.5 on 2026-05-21 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Keluar')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('keterangan', models.CharField(choices=[('Penjualan', 'Penjualan'), ('Lainnya', 'Lainnya')], default='Penjualan', max_length=50, verbose_name='Alasan Keluar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_keluar', to='inventory.barang', verbose_name='Barang')),
            ],
            options={
                'verbose_name': 'Barang Keluar',
                'verbose_name_plural': 'Barang Keluar',
            },
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal Masuk')),
                ('jumlah', models.PositiveIntegerField(verbose_name='Jumlah')),
                ('supplier', models.CharField(max_length=255, verbose_name='Supplier')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barang_masuk', to='inventory.barang', verbose_name='Barang')),
            ],
            options={
                'verbose_name': 'Barang Masuk',
                'verbose_name_plural': 'Barang Masuk',
            },
        ),
    ]
