# Generated by Django 6.0.5 on 2026-05-21 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_kategori_supplier_alter_barang_kategori'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangmasuk',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='barang_masuk', to='inventory.supplier', verbose_name='Supplier'),
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal/Waktu')),
                ('stok_awal', models.IntegerField(verbose_name='Stok Awal')),
                ('stok_akhir', models.IntegerField(verbose_name='Stok Akhir')),
                ('perubahan', models.IntegerField(verbose_name='Perubahan')),
                ('tipe_transaksi', models.CharField(choices=[('MASUK', 'Barang Masuk'), ('KELUAR', 'Barang Keluar'), ('KOREKSI', 'Koreksi Stok'), ('HAPUS_MASUK', 'Hapus Barang Masuk'), ('HAPUS_KELUAR', 'Hapus Barang Keluar')], max_length=20, verbose_name='Tipe Transaksi')),
                ('referensi_id', models.IntegerField(blank=True, null=True, verbose_name='ID Referensi')),
                ('keterangan', models.TextField(verbose_name='Keterangan')),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='inventory.barang', verbose_name='Barang')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Stock Ledger',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-tanggal'],
            },
        ),
    ]
